[project]
name = "ai-agent"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "empy>=4.2",
    "lark-parser>=0.12.0",
    "livekit-agents[cartesia,deepgram,openai,silero,turn-detector]~=1.2",
    "livekit-plugins-noise-cancellation~=0.2",
    "python-dotenv>=1.1.1",
]
